### ISSUE TITLE
ATF used with FragmentScenario breaks testing process

### ISSUE THREAD

**Issue by niehusstaab** [google/Accessibility-Test-Framework-for-Android#25]
Even the most simple of test app I can make is unable to use ATF at its latest version (at the same time as FragmentScenario anyway).
I made a simple demo project to repro the bug: https://github.com/niehusstaab/ATF_bug_demo/tree/master

Attempting to run a basic Espresso test that uses FragmentScenario always results in the following error:
```
java.lang.NoSuchMethodError: No virtual method shouldWaitForActivitiesToComplete()Z in class Landroidx/test/runner/AndroidJUnitRunner; or its super classes (declaration of 'androidx.test.runner.AndroidJUnitRunner' appears in /data/app/com.example.myapplication.test-up9qel7XQQdGcgyDX4V36A==/base.apk)
        at androidx.test.runner.AndroidJUnitRunner.addListenersLegacyOrder(AndroidJUnitRunner.java:442)
        at androidx.test.runner.AndroidJUnitRunner.addListeners(AndroidJUnitRunner.java:423)
        at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:391)
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)
```

Is this a library incompatibility? Or is there some other underlying issue w/in ATF?

**Comment by niehusstaab** [comment]
I've dug in a bit more and managed to get ATF working in my sample (now updated). The issue is DEFINITELY some unknown incompatibility between FragmentScenario and and ATF. The error message is very unhelpful in understanding why.

I'm still not sure which lib is causing the issue, so I'll leave this open. However, I'm inclined to blame FragmentScenario since it's a newer lib and still has some other weirdness going on w/ it (e.g. not being able to import it with `androidTestImplementation` in gradle).

**Comment by niehusstaab** [comment]
Turns out FragmentScenario needed another dependency:
```
debugImplementation 'androidx.fragment:fragment-testing:1.2.5'
debugImplementation 'androidx.test:core:1.3.0-rc01'              // this dep prevents error
```

See full resolution in the android-test repo:
https://github.com/android/android-test/issues/704
