### ISSUE TITLE
Migrate to protobuf-javalite

### ISSUE THREAD

**Issue by Jacks0N23** [google/Accessibility-Test-Framework-for-Android#38]
I have firebase-perf and espresso-contrib (which has dependency on this library) in same classpath so gradle cannot build my project because of duplicate classes from com.google.protobuf:protobuf-lite (from this lib) and com.google.protobuf:protobuf-javalite (from firebase-perf)

[Here is the issue why firebase-perf migrated to javalite](https://github.com/firebase/firebase-android-sdk/issues/1152)

So after u update this lib espresso team also need post a new version with updated deps
And after all @Sloy(or someone else from barista team) should update barista and then I'll can assemble my project :)
(@Sloy I mention you because latest [update(4.1.0) with updating espresso](https://github.com/AdevintaSpain/Barista/issues/431) became breaking)

**Comment by kevinzetterstrom** [comment]
I would like to understand if this is something that will be prioritized, and when it will be prioritized with a fix released that Espresso can pull in, as I am facing a similar issue. 

While I can build my project, my espresso tests fail:
```
java.lang.ExceptionInInitializerError
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:453)
	at java.lang.Class.forName(Class.java:378)
	at com.google.android.gms.internal.cast.zzlu.zzje(com.google.android.gms:play-services-cast@@19.0.0:1)
	at com.google.android.gms.internal.cast.zzlu.<clinit>(com.google.android.gms:play-services-cast@@19.0.0:10)
	at com.google.android.gms.internal.cast.zzlu.zzjf(com.google.android.gms:play-services-cast@@19.0.0:5)
	at com.google.android.gms.internal.cast.zznb.zzd(com.google.android.gms:play-services-cast@@19.0.0:28)
	at com.google.android.gms.internal.cast.zzoa.zze(com.google.android.gms:play-services-cast@@19.0.0:5)
	at com.google.android.gms.internal.cast.zzoa.zzp(com.google.android.gms:play-services-cast@@19.0.0:14)
	at com.google.android.gms.internal.cast.zzmc$zzb.zzjw(com.google.android.gms:play-services-cast@@19.0.0:18)
	at com.google.android.gms.internal.cast.zzmc$zzb.zzjy(com.google.android.gms:play-services-cast@@19.0.0:39)
	at com.google.android.gms.internal.cast.zzmc$zzb.zzjx(com.google.android.gms:play-services-cast@@19.0.0:21)
	at com.google.android.gms.internal.cast.zzmc$zzb.zzjz(com.google.android.gms:play-services-cast@@19.0.0:40)
	at com.google.android.gms.internal.cast.zzo.zzbd(com.google.android.gms:play-services-cast-framework@@19.0.0:103)
	at com.google.android.gms.internal.cast.zzn.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.IllegalStateException: Unable to lookup extension field offset
	at com.google.protobuf.ExtensionSchemaFull.getExtensionsFieldOffset(ExtensionSchemaFull.java:52)
	at com.google.protobuf.ExtensionSchemaFull.<clinit>(ExtensionSchemaFull.java:45)
	... 22 more
```
I can get around the test startup failures by adding
```
configurations {
    forEach { configuration ->
        configuration.exclude(group = "com.google.protobuf", module = "protobuf-lite")
    }
}
```
However, with this startup workaround, when the tests run, the accessibility checks that are backed by [HashMapResultMetadata](https://github.com/google/Accessibility-Test-Framework-for-Android/blob/7ab5fdb5e2cb675edb752c0d0d9cae3986c0bb0c/src/main/java/com/google/android/apps/common/testing/accessibility/framework/HashMapResultMetadata.java), which uses protobuf classes, will silently fail.

Using Espresso to validate accessibility checks are important to us, so our only solution for now is to not update to the latest version of Espresso, and stay on version 3.3. Version 3.3 has a dependency on android.support, which requires us to continue using jetifier, which is not ideal.

**Comment by liutikas** [comment]
The real fix here is for this library to ship a jarjared version of protobuf (whichever version you choose) inside of this library. Adding it as a direct dependency directly without jarjaring causes classpath collisions through various flavors of protobuf available, additionally version upgrades are not safe because protobuf is not binary safe from version to version. All in all, having it as a dependencies causes a huge problem for any client that use protobuf or include a library that does.

**Comment by Jacks0N23** [comment]
@caseyburkhardt can you help us, please?

**Comment by Jacks0N23** [comment]
Close issue because now all dependencies are correct
